# Data Cleaning Project

## Project Objective

The objective of this project is to perform professional-level data cleaning on a deliberately messy dataset. The analysis focuses on identifying missing values, duplicate records, inconsistent formatting, outliers, and incorrect data types.

The cleaned dataset will be prepared for further analysis and saved as a separate CSV file.

## Tools and Technologies

- Python
- Pandas
- NumPy
- Jupyter Notebook

## Data Cleaning Process

1. Load and inspect the dataset
2. Generate a data quality report
3. Handle missing values
4. Remove duplicate records
5. Standardize inconsistent formatting
6. Detect and handle outliers
7. Correct data types
8. Compare data before and after cleaning
9. Save the cleaned dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../dataset/Titanic-Dataset.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.shape

(891, 12)

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

## Initial Data Quality Report

The dataset was inspected to identify data quality issues before performing the cleaning process.

The initial inspection includes:

- Dataset dimensions
- Column names and data types
- Missing values
- Duplicate records
- Numerical descriptive statistics
- Categorical data summary

These checks help determine the cleaning operations required for the dataset.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [10]:
df.describe(include='object')

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

## Missing Value Analysis

Missing values can affect calculations and reduce the quality of analysis. Therefore, missing values were identified and examined before applying any cleaning strategy.

The missing-value count was calculated for each column using `isnull().sum()`.

In [11]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0]

Age         177
Cabin       687
Embarked      2
dtype: int64

In [12]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_report = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Missing Percentage': missing_percentage
})

missing_report[missing_report['Missing Values'] > 0]

          Missing Values  Missing Percentage
Age                  177           19.865320
Cabin                687           77.104377
Embarked               2            0.224467

In [13]:
df['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

### Handling Missing Age Values

The `Age` column contains missing numerical values.

The median was selected to fill the missing Age values because it is less sensitive to extreme values than the mean. This helps preserve the overall distribution of the variable without allowing unusually high or low ages to strongly influence the replacement value.

In [14]:
age_median = df['Age'].median()

df['Age'] = df['Age'].fillna(age_median)

print("Median Age used:", age_median)
print("Remaining missing Age values:", df['Age'].isnull().sum())

Median Age used: 28.0
Remaining missing Age values: 0

In [15]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

### Handling Missing Embarked Values

The `Embarked` column is categorical and contains a small number of missing values.

The mode was selected because it represents the most frequently occurring category in the dataset. This is appropriate for filling a small number of missing categorical values while maintaining the existing category distribution.

In [16]:
embarked_mode = df['Embarked'].mode()[0]

df['Embarked'] = df['Embarked'].fillna(embarked_mode)

print("Mode used:", embarked_mode)
print("Remaining missing Embarked values:", df['Embarked'].isnull().sum())

Mode used: S
Remaining missing Embarked values: 0

### Handling Missing Cabin Values

The `Cabin` column contains a substantial number of missing values.

Instead of replacing the missing cabin numbers with an artificial value, a new binary column named `Cabin_Unknown` was created. It indicates whether cabin information was missing.

The original `Cabin` column is retained because its available information may still be useful for analysis.

In [17]:
df['Cabin_Unknown'] = df['Cabin'].isnull().astype(int)

df[['Cabin', 'Cabin_Unknown']].head()

  Cabin  Cabin_Unknown
0   NaN              1
1   C85              0
2   NaN              1
3  C123              0
4   NaN              1

In [18]:
df.isnull().sum()

PassengerId        0
Survived           0
Pclass             0
Name               0
Sex                0
Age                0
SibSp              0
Parch              0
Ticket             0
Fare               0
Cabin            687
Embarked           0
Cabin_Unknown      0
dtype: int64

## Duplicate Record Handling

Duplicate records can lead to incorrect analysis and may cause some observations to be counted more than once.

The dataset was checked for exact duplicate rows. Any identified duplicate records will be removed while preserving the first occurrence.

In [19]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [20]:
df = df.drop_duplicates().reset_index(drop=True)

print("Dataset shape after removing duplicates:", df.shape)

Dataset shape after removing duplicates: (891, 13)

In [21]:
print("Remaining duplicate rows:", df.duplicated().sum())

Remaining duplicate rows: 0

## Standardizing Inconsistent Formatting

Categorical text values should follow a consistent format. Extra spaces and inconsistent capitalization can create separate categories for values that actually represent the same category.

The categorical columns were inspected and standardized using trimming and consistent capitalization.

In [22]:
print("Sex values:")
print(df['Sex'].unique())

print("\nEmbarked values:")
print(df['Embarked'].unique())

Sex values:
['male' 'female']

Embarked values:
['S' 'C' 'Q']

In [23]:
df['Sex'] = df['Sex'].str.strip().str.lower()

In [24]:
df['Embarked'] = df['Embarked'].str.strip().str.upper()

In [25]:
print("Sex values after standardization:")
print(df['Sex'].unique())

print("\nEmbarked values after standardization:")
print(df['Embarked'].unique())

Sex values after standardization:
['male' 'female']

Embarked values after standardization:
['S' 'C' 'Q']

## Data Type Validation

Correct data types are important for reliable analysis. Numerical columns should be stored as numeric values, while categorical information should be stored as text.

The data types of all columns were checked before applying any necessary corrections.

In [26]:
df.dtypes

PassengerId        int64
Survived           int64
Pclass             int64
Name              object
Sex               object
Age              float64
SibSp              int64
Parch              int64
Ticket            object
Fare             float64
Cabin             object
Embarked          object
Cabin_Unknown      int64
dtype: object

In [27]:
print("Age data type:", df['Age'].dtype)
print("Fare data type:", df['Fare'].dtype)
print("PassengerId data type:", df['PassengerId'].dtype)

Age data type: float64
Fare data type: float64
PassengerId data type: int64

## Outlier Detection Using IQR

Outliers are observations that are unusually far from the majority of values.

The Interquartile Range (IQR) method was used to identify potential outliers in numerical columns.

The IQR is calculated as:

IQR = Q3 - Q1

Lower Bound = Q1 - 1.5 × IQR

Upper Bound = Q3 + 1.5 × IQR

Potential outliers were identified for further investigation rather than automatically deleted.

In [28]:
Q1_age = df['Age'].quantile(0.25)
Q3_age = df['Age'].quantile(0.75)

IQR_age = Q3_age - Q1_age

lower_age = Q1_age - 1.5 * IQR_age
upper_age = Q3_age + 1.5 * IQR_age

age_outliers = df[
    (df['Age'] < lower_age) |
    (df['Age'] > upper_age)
]

print("Age lower bound:", lower_age)
print("Age upper bound:", upper_age)
print("Number of Age outliers:", len(age_outliers))

Age lower bound: 2.5
Age upper bound: 54.5
Number of Age outliers: 66

In [29]:
Q1_fare = df['Fare'].quantile(0.25)
Q3_fare = df['Fare'].quantile(0.75)

IQR_fare = Q3_fare - Q1_fare

lower_fare = Q1_fare - 1.5 * IQR_fare
upper_fare = Q3_fare + 1.5 * IQR_fare

fare_outliers = df[
    (df['Fare'] < lower_fare) |
    (df['Fare'] > upper_fare)
]

print("Fare lower bound:", lower_fare)
print("Fare upper bound:", upper_fare)
print("Number of Fare outliers:", len(fare_outliers))

Fare lower bound: -26.724
Fare upper bound: 65.6344
Number of Fare outliers: 116

### Outlier Handling Decision

Potential outliers were identified using the IQR method.

The identified observations were not automatically removed because statistical outliers may represent genuine observations rather than data-entry errors.

Therefore, the detected outliers were retained unless there was clear evidence that they were invalid values.

## Before vs After Cleaning Summary

The dataset was compared before and after the cleaning process to verify the effect of the data cleaning operations.

The comparison includes:

- Number of rows
- Number of columns
- Missing values
- Duplicate records
- Data types

In [30]:
before_summary = {
    'Rows': 891,
    'Columns': 12
}

after_summary = {
    'Rows': df.shape[0],
    'Columns': df.shape[1]
}

comparison = pd.DataFrame({
    'Before Cleaning': before_summary,
    'After Cleaning': after_summary
})

comparison

         Before Cleaning  After Cleaning
Rows                 891             891
Columns               12              13

## Missing Values: Before vs After

The number of missing values was compared before and after cleaning.

Age and Embarked missing values were handled using median and mode imputation respectively. For Cabin, a separate indicator column was created to preserve information about missing cabin records.

In [31]:
before_missing = 177 + 2 + 687

after_missing = df.isnull().sum().sum()

missing_comparison = pd.DataFrame({
    'Metric': ['Total Missing Values'],
    'Before Cleaning': [before_missing],
    'After Cleaning': [after_missing]
})

missing_comparison

                 Metric  Before Cleaning  After Cleaning
0  Total Missing Values              866             687

In [32]:
before_missing = 866

after_missing = df.isnull().sum().sum()

missing_comparison = pd.DataFrame({
    'Metric': ['Total Missing Values'],
    'Before Cleaning': [before_missing],
    'After Cleaning': [after_missing]
})

missing_comparison

                 Metric  Before Cleaning  After Cleaning
0  Total Missing Values              866             687

## Duplicate Records: Before vs After

Duplicate records were checked before cleaning and removed using the `drop_duplicates()` method.

The final dataset was checked again to confirm that no duplicate rows remain.

In [33]:
duplicate_before = duplicate_count
duplicate_after = df.duplicated().sum()

duplicate_comparison = pd.DataFrame({
    'Metric': ['Duplicate Rows'],
    'Before Cleaning': [duplicate_before],
    'After Cleaning': [duplicate_after]
})

duplicate_comparison

           Metric  Before Cleaning  After Cleaning
0  Duplicate Rows                0               0

## Data Type Validation

The data types of the columns were checked to ensure that numerical variables are stored as numeric values and categorical variables are stored as appropriate text or categorical values.

The dataset was reviewed for data type issues and necessary corrections were applied where required.

In [35]:
dtype_summary = pd.DataFrame({
    'Column': df.columns,
    'Data Type': df.dtypes.astype(str).values
})

dtype_summary

           Column Data Type
0     PassengerId     int64
1        Survived     int64
2          Pclass     int64
3            Name    object
4             Sex    object
5             Age   float64
6           SibSp     int64
7           Parch     int64
8          Ticket    object
9            Fare   float64
10          Cabin    object
11       Embarked    object
12  Cabin_Unknown     int64

## Final Data Quality Report

The cleaned dataset was validated using the following quality checks:

- Total number of rows
- Total number of columns
- Total missing values
- Duplicate records
- Data types

These checks confirm whether the dataset is ready for further analysis.

In [36]:
print("Final Dataset Shape:", df.shape)
print("\nTotal Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Final Dataset Shape: (891, 13)

Total Missing Values: 687
Duplicate Rows: 0

Data Types:
PassengerId        int64
Survived           int64
Pclass             int64
Name              object
Sex               object
Age              float64
SibSp              int64
Parch              int64
Ticket            object
Fare             float64
Cabin             object
Embarked          object
Cabin_Unknown      int64
dtype: object

In [37]:
df.isnull().sum()

PassengerId        0
Survived           0
Pclass             0
Name               0
Sex                0
Age                0
SibSp              0
Parch              0
Ticket             0
Fare               0
Cabin            687
Embarked           0
Cabin_Unknown      0
dtype: int64

In [38]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Cabin_Unknown
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [39]:
df.shape

(891, 13)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PassengerId    891 non-null    int64
 1   Survived       891 non-null    int64
 2   Pclass         891 non-null    int64
 3   Name           891 non-null    object
 4   Sex            891 non-null    object
 5   Age            891 non-null    float64
 6   SibSp          891 non-null    int64
 7   Parch          891 non-null    int64
 8   Ticket         891 non-null    object
 9   Fare           891 non-null    float64
 10  Cabin          204 non-null    object
 11  Embarked       891 non-null    object
 12  Cabin_Unknown  891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

## Export Cleaned Dataset

The cleaned dataset was saved as a new CSV file so that the original raw dataset remains unchanged.

The cleaned file can be used for further analysis and machine learning tasks.

In [41]:
df.to_csv("../output/Titanic_cleaned.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [42]:
cleaned_df = pd.read_csv("../output/Titanic_cleaned.csv")

print("Saved dataset shape:", cleaned_df.shape)
print("Saved dataset loaded successfully.")

Saved dataset shape: (891, 13)
Saved dataset loaded successfully.

In [43]:
cleaned_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Cabin_Unknown
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

## Conclusion

The Titanic dataset was successfully cleaned using a systematic data-cleaning workflow.

The cleaning process included:

- Initial data quality assessment
- Missing-value analysis
- Median imputation for missing Age values
- Mode imputation for missing Embarked values
- Creation of a Cabin_Unknown indicator for missing Cabin information
- Duplicate detection and removal
- Standardization of categorical text values
- Data type validation
- Outlier detection using the IQR method
- Documentation of outlier handling decisions
- Before-and-after data quality comparison
- Final validation of the cleaned dataset
- Exporting the cleaned dataset to a new CSV file

The cleaning decisions were based on the characteristics of each variable rather than applying one method to all columns. The resulting dataset is organized and prepared for further analysis while preserving valid observations.